### ISSUE TITLE
Order of results in MongoDB is not always consistent

### ISSUE THREAD

**Issue by davinov** [ToucanToco/toucan-connectors#164]
One of our users noticed that the order of results was not the expected "natural" one, when querying some data from Mongo Atlas. My guess is that it could come from the fact that Atlas could shard its data across multiple machines, or distribute the query across the replicas (but it's just a guess).

A simple solution would be to add the $natural flag to queries, by default, to ensure the order will always be consistent:
https://docs.mongodb.com/manual/reference/operator/meta/natural/

What do you think about this proposal? Would there be any side-effects I'm not foreseeing, or reasons not want this?

**Comment by piotch** [comment]
I read the doc but I did not understand completly, it is quite short, I think it deserve to be tried in the target context (multi node cluster, with the same sharding options).

The doc mention 'collection scans' does this option have an impact on performance ?

**Comment by davinov** [comment]
Agree, this is definitely not something we should do in this repo ! Closing
