### ISSUE TITLE
Snowflake : apply parameters to query in a secure way

### ISSUE THREAD

**Issue by piotch** [ToucanToco/toucan-connectors#274]
Should not be using `nosql_apply_parameters_to_query` here : https://github.com/ToucanToco/toucan-connectors/blob/master/toucan_connectors/snowflake/snowflake_connector.py#L67

Some digging may be needed as this was not the cas initially but we had to change it : https://github.com/ToucanToco/toucan-connectors/commit/52ffa920f1a016ea29fd9ce70b8c04c84171031c

**Comment by piotch** [comment]
le passsage de paramètres se fait dans la commande `execute` https://docs.snowflake.com/en/user-guide/python-connector-api.html#execute

j'ai vu aussi qu'il y a des méthodes dédiées à pandas dans la lib python : https://docs.snowflake.com/en/user-guide/python-connector-api.html#fetch_pandas_all probablement que ce serait bien au passage d'utiliser cela

**Comment by kadjou1** [comment]
Fixed with #321
