### ISSUE TITLE
Snowflake: Doc links are obsolete

### ISSUE THREAD

**Issue by hachichaud** [ToucanToco/toucan-connectors#292]
The links given as info in the Snowflake connector are obsolete

https://github.com/ToucanToco/toucan-connectors/blob/master/toucan_connectors/snowflake/snowflake_connector.py#L46:L47

https://github.com/ToucanToco/toucan-connectors/blob/master/toucan_connectors/snowflake/snowflake_connector.py#L52

**Comment by f-bb-toucantoco** [comment]
Links are removed
