### ISSUE TITLE
SFTP connector :: add more security

### ISSUE THREAD

**Issue by labynocle** [ToucanToco/toucan-connectors#345]
according to a previous audit, they recommend to enable some points to make this connector more reliable:

* enable SSH private key authentication (instead of using only login/password)
* check the host key to avoid Man in The Middle (MITM) attacks (by definind the supposed ssh fingerprint of the server?)
* The connector should also store securely authentication mechanism and not return them to the user.

**Comment by PrettyWood** [comment]
Moved to peakina
