### ISSUE TITLE
oauth2connector - get_access_token is broken

### ISSUE THREAD

**Issue by CharlesRngrd** [ToucanToco/toucan-connectors#424]
Hi Toucan,

I tried to run the google_sheets_2 quickstart but I faced this error :

![image](https://user-images.githubusercontent.com/52703778/121489135-11929180-c9d4-11eb-8bd6-7218e495c3d0.png)

According to me, the [fix(salesforce): rollback for method get_access_token](https://github.com/ToucanToco/toucan-connectors/commit/258d98f6cac4b57db6d4627b009ce7aa1f086b4d) is responsible for this bug :

![image](https://user-images.githubusercontent.com/52703778/121489525-73eb9200-c9d4-11eb-9db5-5addf80876ca.png)

Could you solve this please ?

Have a nice day

**Comment by f-bb-toucantoco** [comment]
Already solved
