### ISSUE TITLE
oracle sql

### ISSUE THREAD

**Issue by piotch** [ToucanToco/toucan-connectors#66]
There seem to be some good moves on the Oracle side : https://www.oracle.com/technetwork/database/database-technologies/instant-client/overview/index.html

it may be worth updating the connector

**Comment by fspot** [comment]
Also, the `sath89/oracle-xe-11g` docker image is not available anymore.

**Comment by piotch** [comment]
closed by : https://github.com/ToucanToco/toucan-connectors/pull/72
