### ISSUE TITLE
connecteurs nécessitant de visiter une url

### ISSUE THREAD

**Issue by fspot** [ToucanToco/toucan-connectors#73]
Pour obtenir des tokens fonctionnels pour certains connecteurs, il faut aller visiter une url manuellement, ex: google my business → mécanisme oauth.

À terme on aimerait un workflow pour faire ça, mais ça sera un développement qui concernera également tucana et laputa, pas seulement toucan connectors.

**Comment by piotch** [comment]
ATM this is dealt with using this Bearer.sh : https://github.com/ToucanToco/toucan-connectors/pull/129
