### ISSUE TITLE
Test each connector with only its requirements

### ISSUE THREAD

**Issue by virobidou** [ToucanToco/toucan-connectors#92]
Currently, we are testing all connectors with all requirements. The issue is that connectors are sometimes mutually dependent and no error is raised.
Example of PR : https://github.com/ToucanToco/toucan-connectors/pull/91

We should test that a connector is available with only its requirements.

**Comment by piotch** [comment]
@virobidou I'm looking if this could not be done using https://github.com/bndr/pipreqs
